services:
  node1:
    build: .
    container_name: forgechain-node1
    command: ["--port", "9000", "--mine-every", "10", "--reward-address", "5587a231bb6644865e0991de80b77f2704fef489a57c08ddd4059889a46cc8a9"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s
    networks:
      forgechain-net:
        ipv4_address: 172.28.0.11

  node2:
    build: .
    container_name: forgechain-node2
    command: ["--port", "9000", "--connect", "172.28.0.11", "9000", "--mine-every", "2", "--reward-address", "5a53b6fa00bf9277431904cff2bcc9d01139d9f98a85710f1f88b4a9ff89c455"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s
    depends_on:
      node1:
        condition: service_healthy
    networks:
      forgechain-net:
        ipv4_address: 172.28.0.12

  node3:
    build: .
    container_name: forgechain-node3
    command: ["--port", "9000", "--connect", "172.28.0.12", "9000", "--mine-every", "5", "--reward-address", "53a69c93323cbc482fc200c1c2d325a8433f6ae9875d8681adddd3cf35f58f68"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s
    depends_on:
      node2:
        condition: service_healthy
    networks:
      forgechain-net:
        ipv4_address: 172.28.0.13

  node4:
    build: .
    container_name: forgechain-node4
    command: ["--port", "9000", "--connect", "172.28.0.13", "9000", "--mine-every", "10", "--reward-address", "5e225148f60cc5f653a2b2521781651cba849e572b415beda2da158e56c7805b"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s
    depends_on:
      node3:
        condition: service_healthy
    networks:
      forgechain-net:
        ipv4_address: 172.28.0.14

networks:
  forgechain-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
